# Generated by Django 4.0.1 on 2022-04-20 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=15, unique=True)),
                ('receiver', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('correspondence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sender', models.CharField(default='', max_length=15)),
                ('message', models.TextField(default='')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='webapp.chat')),
            ],
            options={
                'db_table': 'correspondence',
                'managed': True,
            },
        ),
    ]
