# Generated by Django 4.0.1 on 2022-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=15)),
                ('name', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
