# Generated by Django 4.0.1 on 2022-04-20 05:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=15, unique=True)),
                ('receiver', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('correspondence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('sender', models.CharField(default='', max_length=15)),
                ('message', models.TextField(default='')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='webapp.chat')),
            ],
        ),
    ]
