# Generated by Django 4.0.1 on 2022-04-20 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_chat_correspondence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
